springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/CreditCard.yaml
    config-url: /v3/api-docs/swagger-config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false